// Generated by https://quicktype.io

import { Owner, Room } from ".";

export interface Reservations {
  status: string;
  isPaid: boolean;
  notes: string;
  endDate: string;
  startDate: string;
  room: Room;
  provider: Owner;
  client: Owner;
  createdAt: string;
  updatedAt: string;
  _id: string;
}
