// Generated by https://quicktype.io

import { ImageModel } from "./image.model";
import { Location } from "./location.model";
import { Owner } from "./owner.model";
import { Service } from "./servcies.model";

export interface Room {
  busy: boolean;
  capacity: number;
  description: string;
  _id: string;
  images: ImageModel[];
  services: Service[];
  name: string;
  nightPrice: number;
  owner: Owner;
  location: Location;
  createdAt: Date;
  updatedAt: Date;
  verified: boolean;
  isFavourite: boolean;
}
